<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Infrastructure\Dao;

use App\Domain\Exception\NotFound;
use App\Domain\Model\CoachSpeciality;
use App\Domain\Repository\CoachSpecialityRepository;
use App\Infrastructure\Dao\Generated\AbstractCoachSpecialityDao;

/**
 * The CoachSpecialityDao class will maintain the persistence of CoachSpeciality class into the coach_specialities table.
 */
class CoachSpecialityDao extends AbstractCoachSpecialityDao implements CoachSpecialityRepository
{
    /**
     * @throws NotFound
     */
    public function mustFindOneById(string $id): CoachSpeciality
    {
        $company = $this->findOne(['id' => $id]);
        if ($company === null) {
            throw new NotFound(CoachSpeciality::class, ['id' => $id]);
        }

        return $company;
    }
}
