<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Infrastructure\Dao;

use App\Domain\Exception\NotFound;
use App\Domain\Model\Event;
use App\Domain\Model\EventRate;
use App\Domain\Model\User;
use App\Domain\Repository\EventRateRepository;
use App\Infrastructure\Dao\Generated\AbstractEventRateDao;

/**
 * The EventRateDao class will maintain the persistence of EventRate class into the events_rates table.
 */
class EventRateDao extends AbstractEventRateDao implements EventRateRepository
{
    /**
     * @throws NotFound
     */
    public function findOneByEventAndUser(Event $event, User $user): ?EventRate
    {
        return $this->findOne(['event_id = :event AND user_id = :user'], [
            'event' => $event->getId(),
            'user' => $user->getId(),
        ]);
    }
}
