<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Infrastructure\Dao;

use App\Domain\Exception\NotFound;
use App\Domain\Model\ProfessionalCategory;
use App\Domain\Repository\ProfessionalCategoryRepository;
use App\Infrastructure\Dao\Generated\AbstractProfessionalCategoryDao;

/**
 * The ProfessionalCategoryDao class will maintain the persistence of ProfessionalCategory class into the professional_categories table.
 */
class ProfessionalCategoryDao extends AbstractProfessionalCategoryDao implements ProfessionalCategoryRepository
{
    public function mustFindOneById(string $id): ProfessionalCategory
    {
        $result = $this->findOne('id = :id', ['id' => $id]);
        if ($result === null) {
            throw new NotFound(ProfessionalCategory::class, ['id' => $id]);
        }

        return $result;
    }

    public function mustFindOneByIdOrLabel(string $id): ProfessionalCategory
    {
        $result = $this->findOne('id = :id OR label = :label', ['id' => $id]);
        if ($result === null) {
            throw new NotFound(ProfessionalCategory::class, ['id' => $id]);
        }

        return $result;
    }
}
