<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Infrastructure\Dao;

use App\Domain\Repository\ProgramOutplacementRepository;
use App\Infrastructure\Dao\Generated\AbstractProgramOutplacementDao;

/**
 * The ProgramOutplacementDao class will maintain the persistence of ProgramOutplacement class into the program_outplacement table.
 */
class ProgramOutplacementDao extends AbstractProgramOutplacementDao implements ProgramOutplacementRepository
{
}
