<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Infrastructure\Dao;

use App\Domain\Exception\NotFound;
use App\Domain\Model\ProgramPic;
use App\Domain\Repository\ProgramPicRepository;
use App\Domain\Repository\UserRepository;
use App\Infrastructure\Dao\Generated\AbstractProgramPicDao;
use App\Infrastructure\Logging\ModelLogger;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use TheCodingMachine\TDBM\TDBMService;

/**
 * The ProgramPicDao class will maintain the persistence of ProgramPic class into the program_pic table.
 */
class ProgramPicDao extends AbstractProgramPicDao implements ProgramPicRepository
{
    use ModelLogger;

    private TokenStorageInterface $tokenStorage;
    private UserRepository $userRepository;

    public function __construct(TDBMService $tdbmService, TokenStorageInterface $tokenStorage, UserRepository $userRepository)
    {
        $this->tokenStorage = $tokenStorage;
        $this->userRepository = $userRepository;
        parent::__construct($tdbmService);
    }

    protected function getTokenStorage(): TokenStorageInterface
    {
        return $this->tokenStorage;
    }

    protected function getUserRepository(): UserRepository
    {
        return $this->userRepository;
    }

    public function save(ProgramPic $programPic): void
    {
        $this->log($programPic);
        parent::save($programPic);
    }

    public function saveNoLog(ProgramPic $programPic): void
    {
        parent::save($programPic);
    }

    public function mustFindOneById(string $id): ProgramPic
    {
        $event = $this->findOne(['id' => $id]);
        if ($event === null) {
            throw new NotFound(ProgramPic::class, ['id' => $id]);
        }

        return $event;
    }

    /**
     * @throws NotFound
     */
    public function mustFindOneByLinkId(string $linkId): ProgramPic
    {
        $program = $this->findOne(['link_id' => $linkId]);
        if ($program === null) {
            throw new NotFound(ProgramPic::class, ['linkId' => $linkId]);
        }

        return $program;
    }

    public function findOneById(string $id): ?ProgramPic
    {
        return $this->findOne(['id' => $id]);
    }
}
