version: '3.7'

services:

  traefik:
    image: traefik:2.0
    command:
      - --providers.docker
      - --providers.docker.exposedByDefault=false
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  webapp:
    image: thecodingmachine/nodejs:12-apache
    labels:
      - traefik.enable=true
      - traefik.http.routers.extranet_router.rule=Host(`${HOST_URL}`)
    environment:
      # Docker image
      STARTUP_COMMAND_0: "npm install"
      STARTUP_COMMAND_1: "npm run build"
      # Vue App
      VUE_APP_LINKEDIN_LINK: "$LINKEDIN_LINK"
      VUE_APP_SITE_OASYS_LINK: "$SITE_OASYS_LINK"
      VUE_APP_TWITTER_LINK: "$TWITTER_LINK"
      VUE_APP_INFO_LINK: "$INFO_LINK"
      VUE_APP_YOUSIGN_SIGNATURE_ID: "8a6daad4-dca7-4307-8f2c-9b8dd115357c"
      VUE_APP_YOUSIGN_URL: "https://staging-app.yousign.com/procedure/sign?"
      VUE_APP_BASE_PARTICIPATION_LINK: "$BASE_PARTICIPATION_LINK"
      VUE_APP_RECAPTCHA_SITE_KEY: "$RECAPTCHA_SITE_KEY"
      # Apollo
      VUE_APP_GRAPHQL_HTTP: "http://api.$HOST_URL/graphql"
      # Apache
      APACHE_DOCUMENT_ROOT: "dist/"
    volumes:
      - ./src/webapp:/var/www/html:rw

  api:
    image: thecodingmachine/php:7.4-v3-apache
    depends_on:
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.api_router.rule=Host(`api.${HOST_URL}`)
    environment:
      # Docker image
      APACHE_DOCUMENT_ROOT: "public/"
      PHP_EXTENSION_XDEBUG: "1"
      PHP_EXTENSION_GD: "1"
      PHP_INI_MEMORY_LIMIT: "1G"
      PHP_INI_UPLOAD_MAX_FILESIZE: "10M"
      PHP_INI_SESSION__GC_MAXLIFETIME: "86400"
      STARTUP_COMMAND_1: "composer install"
      STARTUP_COMMAND_2: "php bin/console doctrine:migrations:migrate -n"
      STARTUP_COMMAND_3: "php bin/console users:create-super-admin"
      STARTUP_COMMAND_4: "php bin/console queue:schedule-events"
      CRON_USER_1: "root"
      CRON_SCHEDULE_1: "*/15 * * * * * *"
      CRON_COMMAND_1: "php bin/console queue:scheduled-worker &"
      # Symfony
      APP_ENV: "dev"
      APP_SECRET: "8d2a5c935d8ef1c0e2b751147382bc75"
      DATABASE_URL: "mysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql:3306/$MYSQL_DATABASE"
      TEST_DATABASE_URL: "mysql://tests:secret@mysql_tests/tests"
      ROOT_PATH: "/var/www/html/"
      MONOLOG_LOGGING_PATH: "php://stderr"
      MODEL_IMPORT_NAME: "modele_import_utilisateurs.xlsx"
      INFO_PDF_NAME: "didacticiel_oasys.pdf"
      # CORS
      CORS_ALLOW_ORIGIN: "$HOST_URL"
      # E-mail
      MAILER_URL: "$MAILER_URL"
      MAILER_FROM: "virginie.charrault@oasys.fr"
      # Super admin
      API_SUPER_ADMIN_FIRST_NAME: "$API_SUPER_ADMIN_FIRST_NAME"
      API_SUPER_ADMIN_LAST_NAME: "$API_SUPER_ADMIN_LAST_NAME"
      API_SUPER_ADMIN_EMAIL: "$API_SUPER_ADMIN_EMAIL"
      API_SUPER_ADMIN_PASSWORD: "$API_SUPER_ADMIN_PASSWORD"
      API_SUPER_ADMIN_PHONE: "$API_SUPER_ADMIN_PHONE"
      RECAPTCHA_SITE_KEY: "$RECAPTCHA_SITE_KEY"
      RECAPTCHA_SECRET_KEY: "$RECAPTCHA_SECRET_KEY"
      SUPPORT_EMAIL: "$SUPPORT_EMAIL"
      # host
      HOST_URL: "$HOST_URL"
      HOST_PROTOCOL: "$HOST_PROTOCOL"
      LINKEDIN_LINK: "$LINKEDIN_LINK"
      SITE_OASYS_LINK: "$SITE_OASYS_LINK"
      TWITTER_LINK: "$TWITTER_LINK"
      YOUSIGN_URL: "$YOUSIGN_URL"
      YOUSIGN_APP: "$YOUSIGN_APP"
      YOUSIGN_TOKEN: "$YOUSIGN_TOKEN"
      YOUSIGN_MODE: "$YOUSIGN_MODE"
      WEBHOOK_YOUSIGN_URL: "$WEBHOOK_YOUSIGN_URL"
      # Redis
      REDIS_SERVER: "redis:6379"
    volumes:
      - ./src/api:/var/www/html:rw

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      MYSQL_DATABASE: "$MYSQL_DATABASE"
      MYSQL_USER: "$MYSQL_USER"
      MYSQL_PASSWORD: "$MYSQL_PASSWORD"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin_router.rule=Host(`db.${HOST_URL}`)
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "$MYSQL_USER"
      PMA_PASSWORD: "$MYSQL_PASSWORD"

  mysql_tests:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "tests"
      MYSQL_USER: "tests"
      MYSQL_PASSWORD: "secret"
    tmpfs:
      - /var/lib/mysql

  redis:
    image: bitnami/redis:5.0
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - redis_data:/bitnami/redis/data

  redisinsight:
    image: redislabs/redisinsight
    labels:
      - traefik.enable=true
      - traefik.http.routers.redis.rule=Host(`redis.oasys.localhost`)
      - traefik.http.routers.redis.service=redis_service
      - traefik.http.services.redis_service.loadbalancer.server.port=8001
    volumes:
      - redisinsight_data:/db

  mailcatcher:
    image: schickling/mailcatcher
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailcatcher_router.rule=Host(`ml.${HOST_URL}`)
      - traefik.http.routers.mailcatcher_router.service=mailcatcher_service
      - traefik.http.services.mailcatcher_service.loadbalancer.server.port=1080

volumes:

  mysql_data:
    driver: local

  redis_data:
    driver: local

  redisinsight_data:
    driver: local
