<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\AbstractCoachSpeciality;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The CoachSpeciality class maps the 'coach_specialities' table in database.
 *
 * @Type
 */
class CoachSpeciality extends AbstractCoachSpeciality
{
}
