<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\AbstractDocumentSigner;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The DocumentSigner class maps the 'documents_signers' table in database.
 *
 * @Type
 */
class DocumentSigner extends AbstractDocumentSigner
{
}
