<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\AbstractProfessionalCategory;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The ProfessionalCategory class maps the 'professional_categories' table in database.
 *
 * @Type
 */
class ProfessionalCategory extends AbstractProfessionalCategory
{
}
