<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\AbstractProgramPic;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The ProgramPic class maps the 'program_pic' table in database.
 *
 * @Type
 */
class ProgramPic extends AbstractProgramPic
{
}
