<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\AbstractProgramOutplacement;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The ProgramOutplacement class maps the 'program_outplacement' table in database.
 *
 * @Type
 */
class ProgramOutplacement extends AbstractProgramOutplacement
{
}
