<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Exception\InvalidStringValue;
use App\Domain\Logging\LoggableModel;
use App\Domain\Model\Generated\AbstractQuestion;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Question class maps the 'questions' table in database.
 *
 * @Type
 */
class Question extends AbstractQuestion implements LoggableModel
{
    /**
     * @throws InvalidStringValue
     */
    public function setTheme(string $theme): void
    {
        $property = 'question';
        InvalidStringValue::notBlank($theme, $property);
        InvalidStringValue::questionTheme($theme, $property);
        parent::setTheme($theme);
    }

    /**
     * @throws InvalidStringValue
     */
    public function setResponse(string $response): void
    {
        $property = 'question';
        InvalidStringValue::notBlank($response, $property);
        parent::setResponse($response);
    }

    /**
     * @throws InvalidStringValue
     */
    public function setQuestion(string $question): void
    {
        $property = 'question';
        InvalidStringValue::notBlank($question, $property);
        InvalidStringValue::length($question, 0, 255, $property);
        parent::setQuestion($question);
    }
}
