<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Exception\InvalidStringValue;
use App\Domain\Logging\LoggableModel;
use App\Domain\Model\Generated\AbstractTodo;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Todo class maps the 'todos' table in database.
 *
 * @Type
 */
class Todo extends AbstractTodo implements LoggableModel
{
    /**
     * @throws InvalidStringValue
     */
    public function setLabel(string $label): void
    {
        InvalidStringValue::notBlank($label);
        parent::setLabel($label);
    }
}
