<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\AbstractVilleFrance;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The VilleFrance class maps the 'villes_france' table in database.
 *
 * @Type
 */
class VilleFrance extends AbstractVilleFrance
{
}
